#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Golang settings
export GOPATH=$HOME/workspace/go
export GCLOUD_SDK=/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk
export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/make/libexec/gnubin:$PATH:$GOPATH/bin:$GCLOUD_SDK/bin
export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:/usr/local/opt/make/libexec/gnuman:$MANPATH

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Source Prezto.
# -s: file exists and not zero size
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# kubectl
if [[ -s "$HOME/.kube/zsh_completion" ]]; then
  source $HOME/.kube/zsh_completion
fi

# gcloud sdk
if [[ -s "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc" ]]; then
  source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
  export PATH=$PATH:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin
fi
export CLOUDSDK_PYTHON=/usr/bin/python

# autojump
if [[ -s /usr/local/etc/profile.d/autojump.sh ]]; then
  source /usr/local/etc/profile.d/autojump.sh
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
