#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Golang settings
export GOPATH=$HOME/workspace/go
export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$GOPATH/bin:$PATH

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Source Prezto.
# -s: file exists and not zero size
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# kubectl
if [[ -s "$HOME/.kube/zsh_completion" ]]; then
  source $HOME/.kube/zsh_completion
fi

# gcloud sdk
if [[ -s "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc" ]]; then
  source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
  export GCLOUD_SDK=/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk
  export PATH=$PATH:$GCLOUD_SDK/bin
  export CLOUDSDK_PYTHON=/usr/bin/python
fi

# autojump
if [[ -s /usr/local/etc/profile.d/autojump.sh ]]; then
  source /usr/local/etc/profile.d/autojump.sh
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# gnu tools
GNU_BIN_PATH=""
GNU_MAN_PATH=""

for P in /usr/local/opt/*/libexec/gnubin; do
  if [ -z "$GNU_BIN_PATH" ]; then
    GNU_BIN_PATH=$P
  else
    GNU_BIN_PATH=$P:$GNU_BIN_PATH
  fi
done

if [ ! -z "$GNU_BIN_PATH" ]; then
  export PATH=$GNU_BIN_PATH:$PATH
fi

for P in /usr/local/opt/*/libexec/gnuman; do
  if [ -z "$GNU_MAN_PATH" ]; then
    GNU_MAN_PATH=$P
  else
    GNU_MAN_PATH=$P:$GNU_MAN_PATH
  fi
done

if [ ! -z "$GNU_MAN_PATH" ]; then
  export MANPATH=$GNU_MAN_PATH:$MANPATH
fi
#export HOMEBREW_GITHUB_API_TOKEN=

export JAVA_8_HOME=$(/usr/libexec/java_home -v1.8)
export JAVA_11_HOME=$(/usr/libexec/java_home -v11)

alias java8='export JAVA_HOME=$JAVA_8_HOME'
alias java11='export JAVA_HOME=$JAVA_11_HOME'

java11

function mmdir() {
  local file=$1
  local dirname=${file%.*}

  mkdir -v ${dirname}
  mv -vi "${file}" "${dirname}"
}
